# Generated by Django 3.2.8 on 2022-01-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HamdyRamzy', '0002_auto_20220130_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='Proficiency',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
