# Generated by Django 3.2.8 on 2022-01-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HamdyRamzy', '0003_language_proficiency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='Proficiency',
            field=models.CharField(blank=True, choices=[('native or bilingual proficiency', 'native or bilingual proficiency'), ('elementary proficiency', 'elementary proficiency'), ('professional working proficiency', 'professional working proficiency'), ('limited working proficiency', 'limited working proficiency'), ('full professional proficiency', 'full professional proficiency')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('Full time', 'Full time'), ('Internship', 'Internship'), ('Part time', 'Part time'), ('Freelancer', 'Freelancer')], max_length=300, null=True),
        ),
    ]
