# Generated by Django 3.2.8 on 2022-01-31 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HamdyRamzy', '0004_auto_20220130_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectpost',
            name='time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='uploaded_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='Proficiency',
            field=models.CharField(blank=True, choices=[('elementary proficiency', 'elementary proficiency'), ('professional working proficiency', 'professional working proficiency'), ('native or bilingual proficiency', 'native or bilingual proficiency'), ('full professional proficiency', 'full professional proficiency'), ('limited working proficiency', 'limited working proficiency')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='projectpost',
            name='uploaded_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('Full time', 'Full time'), ('Part time', 'Part time'), ('Freelancer', 'Freelancer'), ('Internship', 'Internship')], max_length=300, null=True),
        ),
    ]
