# Generated by Django 3.2.8 on 2022-02-01 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HamdyRamzy', '0006_auto_20220201_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpost',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='Proficiency',
            field=models.CharField(blank=True, choices=[('full professional proficiency', 'full professional proficiency'), ('native or bilingual proficiency', 'native or bilingual proficiency'), ('limited working proficiency', 'limited working proficiency'), ('professional working proficiency', 'professional working proficiency'), ('elementary proficiency', 'elementary proficiency')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('Part time', 'Part time'), ('Internship', 'Internship'), ('Full time', 'Full time'), ('Freelancer', 'Freelancer')], max_length=300, null=True),
        ),
    ]
