# Generated by Django 3.2.8 on 2022-02-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HamdyRamzy', '0008_auto_20220208_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactme',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='contactme',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contactme',
            name='subject',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='language',
            name='Proficiency',
            field=models.CharField(blank=True, choices=[('limited working proficiency', 'limited working proficiency'), ('full professional proficiency', 'full professional proficiency'), ('elementary proficiency', 'elementary proficiency'), ('professional working proficiency', 'professional working proficiency'), ('native or bilingual proficiency', 'native or bilingual proficiency')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('Freelancer', 'Freelancer'), ('Full time', 'Full time'), ('Internship', 'Internship'), ('Part time', 'Part time')], max_length=300, null=True),
        ),
    ]
