# Generated by Django 3.2.8 on 2022-02-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HamdyRamzy', '0010_auto_20220211_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='time',
            new_name='views',
        ),
        migrations.AlterField(
            model_name='language',
            name='Proficiency',
            field=models.CharField(blank=True, choices=[('elementary proficiency', 'elementary proficiency'), ('limited working proficiency', 'limited working proficiency'), ('native or bilingual proficiency', 'native or bilingual proficiency'), ('professional working proficiency', 'professional working proficiency'), ('full professional proficiency', 'full professional proficiency')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('Internship', 'Internship'), ('Full time', 'Full time'), ('Part time', 'Part time'), ('Freelancer', 'Freelancer')], max_length=300, null=True),
        ),
    ]
