# Generated by Django 3.2.8 on 2022-02-12 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HamdyRamzy', '0012_auto_20220211_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='Proficiency',
            field=models.CharField(blank=True, choices=[('limited working proficiency', 'limited working proficiency'), ('professional working proficiency', 'professional working proficiency'), ('native or bilingual proficiency', 'native or bilingual proficiency'), ('elementary proficiency', 'elementary proficiency'), ('full professional proficiency', 'full professional proficiency')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='views',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='work',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('Internship', 'Internship'), ('Freelancer', 'Freelancer'), ('Part time', 'Part time'), ('Full time', 'Full time')], max_length=300, null=True),
        ),
    ]
