# Generated by Django 3.2.8 on 2022-02-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HamdyRamzy', '0014_auto_20220212_0658'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('init_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='language',
            name='Proficiency',
            field=models.CharField(blank=True, choices=[('professional working proficiency', 'professional working proficiency'), ('full professional proficiency', 'full professional proficiency'), ('native or bilingual proficiency', 'native or bilingual proficiency'), ('limited working proficiency', 'limited working proficiency'), ('elementary proficiency', 'elementary proficiency')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('Internship', 'Internship'), ('Freelancer', 'Freelancer'), ('Full time', 'Full time'), ('Part time', 'Part time')], max_length=300, null=True),
        ),
    ]
