# Generated by Django 3.2.8 on 2022-02-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HamdyRamzy', '0016_auto_20220212_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='last_visit',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='Proficiency',
            field=models.CharField(blank=True, choices=[('full professional proficiency', 'full professional proficiency'), ('native or bilingual proficiency', 'native or bilingual proficiency'), ('limited working proficiency', 'limited working proficiency'), ('elementary proficiency', 'elementary proficiency'), ('professional working proficiency', 'professional working proficiency')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('Full time', 'Full time'), ('Internship', 'Internship'), ('Part time', 'Part time'), ('Freelancer', 'Freelancer')], max_length=300, null=True),
        ),
    ]
