# Generated by Django 3.2.8 on 2022-02-13 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HamdyRamzy', '0018_auto_20220212_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactme',
            name='sender',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='language',
            name='Proficiency',
            field=models.CharField(blank=True, choices=[('elementary proficiency', 'elementary proficiency'), ('professional working proficiency', 'professional working proficiency'), ('full professional proficiency', 'full professional proficiency'), ('native or bilingual proficiency', 'native or bilingual proficiency'), ('limited working proficiency', 'limited working proficiency')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='viewer',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='work',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('Full time', 'Full time'), ('Internship', 'Internship'), ('Part time', 'Part time'), ('Freelancer', 'Freelancer')], max_length=300, null=True),
        ),
    ]
