# Generated by Django 3.2.8 on 2022-02-17 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HamdyRamzy', '0020_auto_20220216_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='Proficiency',
            field=models.CharField(blank=True, choices=[('professional working proficiency', 'professional working proficiency'), ('elementary proficiency', 'elementary proficiency'), ('native or bilingual proficiency', 'native or bilingual proficiency'), ('limited working proficiency', 'limited working proficiency'), ('full professional proficiency', 'full professional proficiency')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('Full time', 'Full time'), ('Freelancer', 'Freelancer'), ('Internship', 'Internship'), ('Part time', 'Part time')], max_length=300, null=True),
        ),
        migrations.CreateModel(
            name='Project_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(null=True, upload_to='project pictures/%y/%m/%d')),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='HamdyRamzy.projectpost')),
            ],
        ),
    ]
