# Generated by Django 3.2.8 on 2022-02-19 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HamdyRamzy', '0022_auto_20220218_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='type',
            field=models.CharField(blank=True, default='blog_post', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='projectpost',
            name='type',
            field=models.CharField(blank=True, default='project_post', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='Proficiency',
            field=models.CharField(blank=True, choices=[('native or bilingual proficiency', 'native or bilingual proficiency'), ('elementary proficiency', 'elementary proficiency'), ('full professional proficiency', 'full professional proficiency'), ('professional working proficiency', 'professional working proficiency'), ('limited working proficiency', 'limited working proficiency')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('Freelancer', 'Freelancer'), ('Internship', 'Internship'), ('Part time', 'Part time'), ('Full time', 'Full time')], max_length=300, null=True),
        ),
    ]
